apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: qover-app
  namespace: qover
spec:
  ingressClassName: nginx
  rules:
    - host: qover.127.0.0.1.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: qover-app
                port:
                  number: 80
