apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: qover-app-role
  namespace: qover
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["mongo-auth"]
    verbs: ["get"]
