apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: qover-app-rolebinding
  namespace: qover
subjects:
  - kind: ServiceAccount
    name: qover-app
    namespace: qover
roleRef:
  kind: Role
  name: qover-app-role
  apiGroup: rbac.authorization.k8s.io
