apiVersion: v1
kind: Service
metadata:
  name: qover-app
  namespace: qover
  labels:
    app: qover-app
spec:
  selector:
    app: qover-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
