apiVersion: v2
name: observability
description: Observability stack for qover-sre-challenge
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
  - name: kube-prometheus-stack
    version: 58.3.1
    repository: https://prometheus-community.github.io/helm-charts
  - name: loki
    version: 5.41.0
    repository: https://grafana.github.io/helm-charts
  - name: tempo
    version: 1.10.1
    repository: https://grafana.github.io/helm-charts
