apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: qover-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/AntonioJordan/qover-sre-challenge.git
    targetRevision: main
    path: k8s/app
  destination:
    server: https://kubernetes.default.svc
    namespace: qover
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
